name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'    # 每天 UTC 零点运行一次
  workflow_dispatch:       # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Sprinining            # 你的 GitHub 用户名
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
          theme: github-dark
          color_snake: '#00ffcc'                  # 蛇的颜色
          color_dots: '#000000,#111111,#222222,#333333,#444444'  # 更暗的背景方块色
          gif_quality: 90
          frame_duration: 150
          hide_title: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contribution-snake
          path: dist/

      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake.gif
          git commit -m "Update contribution snake"
          git push
        env:
          # 这里确保用的是你的 GitHub Token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
