name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0 点运行
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Sprinining
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - uses: actions/upload-artifact@v4
        with:
          name: snake-graphic
          path: dist
