name: Generate Contribution Snake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate contribution snake
        uses: platane/snk@v3
        with:
          github_user_name: Sprinining
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
          theme: github-dark
          color_snake: '#00ffcc'
          color_dots: '#111111,#333333,#555555,#777777,#999999'
          gif_quality: 90
          frame_duration: 150
          hide_title: true

      - name: Upload contribution snake artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contribution-snake
          path: dist/
